language: csharp
mono: none
sudo: required
dotnet: 3.0
script:
    - dotnet restore
    - dotnet build
    - dotnet test tests/Challenge.Tests/Challenge.Tests.csproj
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1